# Generated by Django 5.2.2 on 2025-06-10 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0011_commission'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='supabase_proof_of_payment_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='maintenancepayment',
            name='supabase_proof_screenshot_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='supabase_proof_of_payment_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
