# Generated by Django 5.2.2 on 2025-06-10 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_user_myapp_user_country_b53529_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='activationfeeproof',
            name='supabase_proof_image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
