# Generated by Django 5.2.2 on 2025-06-10 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='supabase_image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
